title: EvanSky
subtitle: 今天你学习了吗
description: 今天你学习了吗
keywords: null
author: EvanSky
language: zh-CN
timezone: ''
url: https://note.webhy.cn/
permalink: posts/:abbrlink.html
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight: # 代码高亮
  enable: true # 是否开启
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
index_generator:
  path: ''
  per_page: 8
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime
per_page: 10
pagination_dir: page
include: [ ]
exclude: [ ]
ignore: null
theme: butterfly
deploy:
  type: git
  repo: https://github.com/evanhy/evanhy.github.io
  repository: git@github.com:evanhy/evanhy.github.io.git
  branch: main
  token: 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
live2d:
  enable: false
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    use: live2d-widget-model-haruto
  display:
    position: right
    width: 150
    height: 300
  mobile:
    show: true
  react:
    opacity: 0.7
search:
  path: search.xml
  field: post
  content: true
lazyload:
  enable: false
  loadingImg: /img/loading.gif
hide_posts:
  filter: hide
  public_generators: [ ]
  noindex: true